todoclassproject/todoclass/classapp/urls.py
from unicodedata import name
from django.urls import path
from . import views
app_name='classapp'

urlpatterns=[
    path('home/',views.TaskListView.as_view(),name="home"),

    path('show/<int:pk>/',views.TaskDetailtView.as_view(),name="show"),

    path('update/<int:pk>/',views.TaskUpdateView.as_view(),name="update"),

    path('delete/<int:pk>/',views.TaskDeletetView.as_view(),name="delete")

    ]

todoclassproject/todoclass/todoclass/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('classapp.urls'))
]

todoclassproject/todoclass/classapp/models.py
from django.db import models


class TodoModel(models.Model):
    name = models.CharField(max_length=60)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoclassproject/todoclass/classapp/forms.py
from django import forms
from .models import TodoModel


class TodoForm(forms.ModelForm):
    class Meta:
        model=TodoModel
        fields=['name','priority','date']

todoclassproject/todoclass/classapp/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import TodoForm
from . models import *

from  django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

class TaskListView(ListView):
    model = TodoModel
    template_name = 'main.html'
    context_object_name = 'task'

    
class TaskDetailtView(DetailView):
    model = TodoModel
    template_name = 'show.html'
    context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model = TodoModel
    template_name = 'edit.html'
    context_object_name = 'task'
    fields = ['name','priority','date']

    def get_success_url(self):
        return reverse_lazy('classapp:show',kwargs={'pk':self.object.id})


class TaskDeletetView(DeleteView):
    model = TodoModel
    template_name = 'delete.html'
    success_url = reverse_lazy('classapp:show')

todoclassproject/todoclass/templates/delete.html
{% extends 'home.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure to delete this task?,is it completed?</p>
    <button type="submit" class="btn btn-success">confirm</button>
</form>
{% endblock%}

todoclassproject/todoclass/templates/edit.html
{% extends 'home.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            task updated
            <div class="card-body">
               <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">update</button>
               </form>
            </div>
        </div>
    </div>
</div>





{% endblock %}

todoclassproject/todoclass/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homestyle.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h4>ToDo</h4>

                </div>
            </div>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}

</body>
</html>

todoclassproject/todoclass/templates/main.html
{% extends 'home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="shadow-lg p-3 mb-5 bg-white rounded" >

            <form action="" method="post" class="p3-shadow">
                    {% csrf_token %}
                <div class="form-group">
                      <input type="text" class="form-control" name="name" placeholder="enter your task name">

                </div>
                  <div class="form-group">
                      <input type="number" class="form-control" name="priority" placeholder="enter your priority">

                </div>
                 <div class="form-group">
                      <input type="date" class="form-control" name="date" placeholder="enter your date">

                </div>
                  <button type="submit" class="btn btn-success">Add</button>


            </form>
                </div>




        </div>





</div>
</div>

{% endblock %}

todoclassproject/todoclass/templates/show.html
{% extends 'home.html' %}
{% block content %}



            <div class="shadow p-3 mb-5 bg-black rounded" >


            <div class="card" >

                <div class="card-body">
                    <h5 class="card-title">{{task.name}}</h5>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
                         <a class="btn btn-success" href="{% url 'classapp:delete' task.id %}">Delete</a>
                    <a class="btn btn-success" href="{% url 'classapp:update' task.id %}">Update</a>
                </div>
            </div>
        </div>


{% endblock %}